workspace '../BuddySDK.xcworkspace'
xcodeproj 'Lib/BuddySDK.xcodeproj'

target :'BuddySDK Unit Tests', :exclusive => true do
    pod 'Kiwi/XCTest', '2.2.3'
end

#pod 'AFNetworking'
#pod 'ObjectiveSugar'