workspace '../BuddySDK.xcworkspace'
xcodeproj 'Lib/BuddySDK.xcodeproj'
xcodeproj 'BuddySocial/BuddySocial.xcodeproj'

target :'BuddySDK Unit Tests', :exclusive => true do
    pod 'Kiwi/XCTest', '2.2.4'
    xcodeproj 'Lib/BuddySDK.xcodeproj'
end

target :'BuddySocial', :exclusive => true do
    pod 'BuddySDK'
    xcodeproj 'BuddySocial/BuddySocial.xcodeproj'
end